[package]
name = "remote"
version = "0.1.0"
authors = ["Mikkel-T <mikkel@mikkel-t.com>"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.2"
autopilot = "0.4"
futures-util = { version = "0.3", default-features = false, features = ["sink"] }